// ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".
import * as path from 'path';
import * as lambda from 'aws-cdk-lib/aws-lambda';
import { Construct } from 'constructs';

/**
 * Props for RetrieveIitFunction
 */
export interface RetrieveIitFunctionProps extends lambda.FunctionOptions {
}

/**
 * An AWS Lambda function which executes src/retrieve-iit/retrieve-iit.
 */
export class RetrieveIitFunction extends lambda.Function {
  constructor(scope: Construct, id: string, props?: RetrieveIitFunctionProps) {
    super(scope, id, {
      description: 'src/retrieve-iit/retrieve-iit.lambda.ts',
      ...props,
      runtime: new lambda.Runtime('nodejs20.x', lambda.RuntimeFamily.NODEJS),
      handler: 'index.handler',
      code: lambda.Code.fromAsset(path.join(__dirname, '../../assets/retrieve-iit/retrieve-iit.lambda')),
    });
    this.addEnvironment('AWS_NODEJS_CONNECTION_REUSE_ENABLED', '1', { removeInEdge: true });
  }
}